[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] active: 
  data-integrator/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:40:42Z

App              Version  Status  Scale  Charm            Channel        Rev  Address         Exposed  Message
application               active      1  application                       0                  no       
config-server             active      1  mongodb-k8s      6/edge          60  10.152.183.213  no       
data-integrator           active      1  data-integrator  latest/stable   41  10.152.183.130  no       
mongos-k8s                active      1  mongos-k8s                        0  10.152.183.121  no       
shard0                    active      1  mongodb-k8s      6/edge          60  10.152.183.252  no       

Unit                Workload  Agent  Address       Ports  Message
application/0*      active    idle                        
config-server/0*    active    idle   10.1.151.205         Primary
data-integrator/0*  active    idle   10.1.151.209         
mongos-k8s/0*       active    idle   10.1.151.200         
shard0/0*           active    idle   10.1.151.206         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-config-server-0: 01:33:35 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard shard0 to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1729647215, 1), 'signature': {'hash': b'\\xd2\\xc1\\x0b\\x1eP\\x1d\\x98\\x02e\\xf7\\x03\\xbaWK\\xb0\\x81a\\xdc\\xc0\\xc6', 'keyId': 7428777985819279385}}, 'operationTime': Timestamp(1729647215, 1)}")
unit-config-server-0: 01:33:35 ERROR unit.config-server/0.juju-log config-server:6: shard0 shard does not have the same auth as the config server.
unit-mongos-k8s-0: 01:35:17 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.
unit-mongos-k8s-0: 01:36:19 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.
unit-mongos-k8s-0: 01:39:24 ERROR unit.mongos-k8s/0.juju-log External configuration: nonsensical-setting for expose-external is not valid, should be one of: ['none', 'nodeport']

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...