[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:36:39Z

App            Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
application             active      1  application             0                  no       
config-server           active      1  mongodb-k8s  6/edge    59  10.152.183.140  no       
mongos-k8s              active      1  mongos-k8s              0  10.152.183.137  no       
shard0                  active      1  mongodb-k8s  6/edge    59  10.152.183.238  no       

Unit              Workload  Agent  Address      Ports  Message
application/0*    active    idle                       
config-server/0*  active    idle   10.1.228.16         Primary
mongos-k8s/0*     active    idle   10.1.228.10         
shard0/0*         active    idle   10.1.228.15         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-config-server-0: 01:31:55 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard shard0 to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1729474314, 2), 'signature': {'hash': b'1c\\x8a\\x89W\\xd9\\xc5\\n\\xd3\\x08\\xb4V\\x00\\x08\\xe9r/%\\x84\\xf1', 'keyId': 7428035390268768281}}, 'operationTime': Timestamp(1729474314, 2)}")
unit-config-server-0: 01:31:55 ERROR unit.config-server/0.juju-log config-server:6: shard0 shard does not have the same auth as the config server.
unit-mongos-k8s-0: 01:33:36 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.
unit-mongos-k8s-0: 01:34:39 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...